import {init,defaultDevice,np,forward,normalizeConfig} from './forward.js'
const $=x=>document.getElementById(x),S={}
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]))
function ids(x){if(Array.isArray(x))return x.map(y=>Number(y?.token_id??y));x=String(x||'').trim();if(!x)return[];return ids(x[0]=='['?JSON.parse(x):x.split(/[\s,]+/).filter(Boolean))}
function product(a){return a.reduce((x,y)=>x*y,1)}
function f32(a){return new Float32Array(a.slice().buffer)}
function unpack(b,e,d){let p=b.subarray(d+e.offset,d+e.offset+e.packed_bytes),s=f32(b.subarray(d+e.scales_offset,d+e.scales_offset+e.scales_nbytes)),sh=e.shape,q=e.name.includes('/kernel')||e.name.includes('/mhc_phi_'),n=q?sh.at(-2):sh.at(-1),c=q?sh.at(-1):1,r=product(sh)/(n*c),o=new Float32Array(product(sh)),k=0;for(let i=0;i<r;i++)for(let j=0;j<c;j++){let z=i*n*c+j;for(let st=0;st<n;st+=e.group_size){let sc=s[k++],en=Math.min(n,st+e.group_size);for(let t=st;t<en;t++){let u=z+t*c,v=((p[u>>1]>>((u&1)*4))&15)-8;o[u]=v*sc}}}return np.array(o,{dtype:np.float32}).reshape(sh)}
async function loadW4(){let r=await fetch('./w4-packed.bin',{cache:'no-store'});if(!r.ok)throw Error(`W4 HTTP ${r.status}`);let b=new Uint8Array(await r.arrayBuffer());if(new TextDecoder().decode(b.subarray(0,10))!=='NEEDLEJS1')throw Error('bad W4 magic');let v=new DataView(b.buffer),hl=v.getUint32(10,true),hs=14,h=JSON.parse(new TextDecoder().decode(b.subarray(hs,hs+hl))),d=hs+hl,w={};for(let e of h.tensors){let raw=e.encoding==='w4'?null:f32(b.subarray(d+e.offset,d+e.offset+e.nbytes));w[e.name]=raw?np.array(raw,{dtype:np.float32}).reshape(e.shape):unpack(b,e,d)}return{h,w}}
function text(i){return S.meta[+i]?.token_text||''}
function top(a,n=8){return Array.from(a).map((logit,token_id)=>({token_id,logit:Number(logit),token_text:text(token_id)})).sort((x,y)=>y.logit-x.logit).slice(0,n)}
function probs(a,t){t=Math.max(1e-5,t);let m=Math.max(...a),p=Float64Array.from(a,x=>Math.exp((x-m)/t)),z=p.reduce((x,y)=>x+y,0);for(let i=0;i<p.length;i++)p[i]/=z;return p}
function pick(a,t,tp){let p=probs(a,t),q=Array.from(p,(probability,token_id)=>({token_id,probability})).sort((x,y)=>y.probability-x.probability),k=[],z=0;for(let x of q){k.push(x);z+=x.probability;if(z>=tp)break}let r=Math.random()*z;for(let x of k){r-=x.probability;if(r<=0)return x}return k.at(-1)}
function render(){ $('tokens').innerHTML=S.tokens.map((x,i)=>`<span class="token"><b>${i}</b> ${x} <span class="muted">${esc(text(x))}</span></span>`).join('');$('trajectory').innerHTML=S.traj.map(x=>`<div class="row"><div>${x.step}</div><div>${x.token_id}</div><div>${esc(x.token_text)||'∅'}</div><div>${x.probability.toFixed(4)}</div></div>`).join('')||'—'}
async function logits(t){let k=t.join(',');if($('kv').checked&&S.cache.has(k))return S.cache.get(k);let x=np.array(Int32Array.from(t),{dtype:np.int32}).reshape([1,t.length]),o=forward(x,S.cfg,S.w),a=new Float32Array(o.ref.dataSync()),z=a.slice(a.length-S.cfg.vocab_size);if($('kv').checked)S.cache.set(k,z);return z}
async function sample(){let t=ids($('prompt').value),n=Math.min(128,Math.max(1,+$('steps').value||24)),temp=Math.max(0,+$('temperature').value||.8),tp=Math.min(1,Math.max(.01,+$('topP').value||.95));if(!t.length)throw Error('请输入 token ids');S.tokens=t.slice();S.traj=[];render();for(let step=1;step<=n;step++){let a=await logits(S.tokens),p=probs(a,temp),best=top(a);$('topk').innerHTML=best.map((x,i)=>`<div class="row"><div>#${i+1}</div><div>${x.token_id}</div><div>${esc(x.token_text)||'∅'}</div><div>${(p[x.token_id]*100).toFixed(3)}%</div></div>`).join('');let x=pick(a,temp,tp);S.traj.push({step,token_id:x.token_id,token_text:text(x.token_id),probability:x.probability});S.tokens.push(x.token_id);render();$('status').textContent=`采样 ${step}/${n} · cache=${$('kv').checked?'on':'off'}`;await new Promise(requestAnimationFrame)}$('status').className='status ok';$('status').textContent=`完成：${n} tokens；KV session cache=${$('kv').checked?'enabled':'disabled'}；entries=${S.cache.size}`}
async function initApp(){try{let dev=(await init('wasm')).includes('wasm')?'wasm':'cpu';defaultDevice(dev);let x=await loadW4();S.h=x.h;S.w=x.w;S.cfg=normalizeConfig(x.h.config??x.h);S.meta=x.h.token_metadata||[];let p=await(await fetch('./prefill.json')).json();$('prompt').value=JSON.stringify(ids(p));$('summary').textContent=`${x.h.tensors.length} tensors · W4 · ${dev} · vocab=${S.cfg.vocab_size}`;$('status').className='status ok';$('status').textContent='W4 已加载。'}catch(e){$('status').className='status bad';$('status').textContent='加载失败：'+e.message}}
$('sample').onclick=async()=>{try{$('sample').disabled=true;await sample()}catch(e){$('status').className='status bad';$('status').textContent='采样失败：'+e.message}finally{$('sample').disabled=false}}
$('reset').onclick=()=>{S.cache.clear();S.tokens=ids($('prompt').value);S.traj=[];render();$('status').textContent='cache 已清空'}
$('kv').onchange=()=>{if(!$('kv').checked)S.cache.clear()};initApp()
